Using a default base image is not recommended
The last thing we want is for us to have a typo in the CI yml and have
fedora:34 images when we think we should have fedora 35 and everything
be green.

diff --git a/.github/workflows/bb_containers.yml b/.github/workflows/bb_containers.yml
--- a/.github/workflows/bb_containers.yml
+++ b/.github/workflows/bb_containers.yml
@@ -98,6 +98,10 @@ jobs:
       - name: Set up env vars
         run: |
           set -vx
+          [[ -n "${{ matrix.image }}" ]] || {
+            echo "Missing base image (FROM)"
+            exit 1
+          }
           TAG_TMP=${{ matrix.image }}
           if [[ $TAG_TMP = "ubi8" ]]; then
             echo "TAG=rhel8" >>$GITHUB_ENV
